name: Build Chrome extension
run-name: Build Chrome extension '${{ inputs.tag || 'latest' }}'

on:
  push:
    branches:
      - main

permissions:
  contents: write   # Needed for creating releases

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Zip extension
        run: |
          zip -r job-filter-extension.zip ./ -x "*.git*" "*.github*"
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: job-filter-extension.zip